In [ ]:
!pip install pandas numpy requests sqlalchemy pymysql
import pandas as pd
import numpy as np
import requests

url = "https://earthquake.usgs.gov/fdsnws/event/1/query"

all_data = []

for year in range(2021, 2026):

    for month in range(1, 13):

        start_date = f"{year}-{month:02d}-01"

        if month == 12:
            end_date = f"{year + 1}-01-01"
        else:
            end_date = f"{year}-{month + 1:02d}-01"

        params = {
            "format": "geojson",
            "starttime": start_date,
            "endtime": end_date,
            "limit": 20000,
            "orderby": "time-asc"
        }

        print(f"Downloading: {start_date} to {end_date}")

        response = requests.get(url, params=params, timeout=60)

        if response.status_code != 200:
            print("ERROR:", response.status_code)
            print(response.text)
            continue

        data = response.json()

        for earthquake in data["features"]:

            properties = earthquake["properties"]
            geometry = earthquake["geometry"]

            coordinates = geometry["coordinates"]

            longitude = coordinates[0]
            latitude = coordinates[1]
            depth_km = coordinates[2]

            all_data.append({
                "id": earthquake.get("id"),

                "time": properties.get("time"),

                "updated": properties.get("updated"),

                "latitude": latitude,

                "longitude": longitude,

                "depth_km": depth_km,

                "mag": properties.get("mag"),

                "magType": properties.get("magType"),

                "place": properties.get("place"),

                "status": properties.get("status"),

                "tsunami": properties.get("tsunami"),

                "alert": properties.get("alert"),

                "felt": properties.get("felt"),

                "cdi": properties.get("cdi"),

                "mmi": properties.get("mmi"),

                "sig": properties.get("sig"),

                "net": properties.get("net"),

                "code": properties.get("code"),

                "ids": properties.get("ids"),

                "sources": properties.get("sources"),

                "types": properties.get("types"),

                "nst": properties.get("nst"),

                "dmin": properties.get("dmin"),

                "rms": properties.get("rms"),

                "gap": properties.get("gap"),

                "type": properties.get("type")
            })

print("Download completed.")

df = pd.DataFrame(all_data)

print("Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nFirst 5 rows:")
display(df.head())

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: pandas in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.6)
Requirement already satisfied: numpy in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.5.3)
Requirement already satisfied: requests in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.34.2)
Requirement already satisfied: sqlalchemy in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.1.1)
Requirement already satisfied: pymysql in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (1.2.3)
Requirement already satisfied: python-dateutil>=2.8.2 in .\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.4)
Requirement already satisfied: charset_normalizer<4,>=2 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests) (3.19)
Requirement already satisfied: urllib3<3,>=1.26 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests) (2026.7.22)
Requirement already satisfied: typing-extensions>=4.6.0 in .\AppData\Roaming\Python\Python314\site-packages (from sqlalchemy) (4.16.0)
Requirement already satisfied: six>=1.5 in .\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading: 2021-01-01 to 2021-02-01
Downloading: 2021-02-01 to 2021-03-01
Downloading: 2021-03-01 to 2021-04-01
Downloading: 2021-04-01 to 2021-05-01
Downloading: 2021-05-01 to 2021-06-01
Downloading: 2021-06-01 to 2021-07-01
Downloading: 2021-07-01 to 2021-08-01
Downloading: 2021-08-01 to 2021-09-01
Downloading: 2021-09-01 to 2021-10-01
Downloading: 2021-10-01 to 2021-11-01
Downloading: 2021-11-01 to 2021-12-01
Downloading: 2021-12-01 to 2022-01-01
Downloading: 2022-01-01 to 2022-02-01
Downloading: 2022-02-01 to 2022-03-01
Downloading: 2022-03-01 to 2022-04-01
Downloading: 2022-04-01 to 2022-05-01
Downloading: 2022-05-01 to 2022-06-01
Downloading: 2022-06-01 to 2022-07-01
Downloading: 2022-07-01 to 2022-08-01
Downloading: 2022-08-01 to 2022-09-01
Downloading: 2022-09-01 to 2022-10-01
Downloading: 2022-10-01 to 2022-11-01
Downloading: 2022-11-01 to 2022-12-01
Downloading: 2022-12-01 to 2023-01-01
Downloading: 2023-01-01 to 2023-02-01
Downloading: 2023-02-01 to 2023-03-01
Downloading: 2023-03-01 to 2023-04-01
Downloading: 2023-04-01 to 2023-05-01
Downloading: 2023-05-01 to 2023-06-01
Downloading: 2023-06-01 to 2023-07-01
Downloading: 2023-07-01 to 2023-08-01
Downloading: 2023-08-01 to 2023-09-01
Downloading: 2023-09-01 to 2023-10-01
Downloading: 2023-10-01 to 2023-11-01
Downloading: 2023-11-01 to 2023-12-01
Downloading: 2023-12-01 to 2024-01-01
Downloading: 2024-01-01 to 2024-02-01
Downloading: 2024-02-01 to 2024-03-01
Downloading: 2024-03-01 to 2024-04-01
Downloading: 2024-04-01 to 2024-05-01
Downloading: 2024-05-01 to 2024-06-01
Downloading: 2024-06-01 to 2024-07-01
Downloading: 2024-07-01 to 2024-08-01
Downloading: 2024-08-01 to 2024-09-01
Downloading: 2024-09-01 to 2024-10-01
Downloading: 2024-10-01 to 2024-11-01
Downloading: 2024-11-01 to 2024-12-01
Downloading: 2024-12-01 to 2025-01-01
Downloading: 2025-01-01 to 2025-02-01
Downloading: 2025-02-01 to 2025-03-01
Downloading: 2025-03-01 to 2025-04-01
Downloading: 2025-04-01 to 2025-05-01
Downloading: 2025-05-01 to 2025-06-01
Downloading: 2025-06-01 to 2025-07-01
Downloading: 2025-07-01 to 2025-08-01
Downloading: 2025-08-01 to 2025-09-01
Downloading: 2025-09-01 to 2025-10-01
Downloading: 2025-10-01 to 2025-11-01
Downloading: 2025-11-01 to 2025-12-01
Downloading: 2025-12-01 to 2026-01-01
Download completed.
Shape: (762117, 26)

Columns:
['id', 'time', 'updated', 'latitude', 'longitude', 'depth_km', 'mag', 'magType', 'place', 'status', 'tsunami', 'alert', 'felt', 'cdi', 'mmi', 'sig', 'net', 'code', 'ids', 'sources', 'types', 'nst', 'dmin', 'rms', 'gap', 'type']

First 5 rows:

,id,time,updated,latitude,longitude,depth_km,mag,magType,place,status,...,net,code,ids,sources,types,nst,dmin,rms,gap,type
0,pr2021001027,1609459299400,1611999858313,17.995100,-67.0525,5.00,1.75,md,"2 km NNW of La Parguera, Puerto Rico",reviewed,...,pr,2021001027,",pr2021001027,",",pr,",",origin,phase-data,",4.0,0.0270,0.08,120.0,earthquake
1,nc73505360,1609459450210,1609797306182,38.047333,-118.7285,5.25,1.89,md,"31km SE of Bodie, CA",reviewed,...,nc,73505360,",nc73505360,",",nc,",",nearby-cities,origin,phase-data,scitech-link,",26.0,0.2693,0.09,90.0,earthquake
2,pr2021001028,1609459939760,1611999881681,17.976000,-66.8420,13.00,1.89,md,"3 km SW of Indios, Puerto Rico",reviewed,...,pr,2021001028,",pr2021001028,",",pr,",",origin,phase-data,",6.0,0.2023,0.11,208.0,earthquake
3,pr2021001029,1609460047580,1611999899873,19.063100,-66.8555,8.00,3.14,md,"63 km N of Hatillo, Puerto Rico",reviewed,...,pr,2021001029,",pr2021001029,",",pr,",",origin,phase-data,",16.0,0.6482,0.52,284.0,earthquake
4,pr2021001030,1609460184950,1612080776411,17.967600,-66.8720,19.00,1.66,md,"2 km ESE of Maria Antonia, Puerto Rico",reviewed,...,pr,2021001030,",pr2021001030,",",pr,",",origin,phase-data,",4.0,0.1722,0.10,303.0,earthquake

In [19]:
print(df.columns.tolist())

['id', 'time', 'updated', 'latitude', 'longitude', 'depth_km', 'mag', 'magType', 'place', 'status', 'tsunami', 'alert', 'felt', 'cdi', 'mmi', 'sig', 'net', 'code', 'ids', 'sources', 'types', 'nst', 'dmin', 'rms', 'gap', 'type']

In [20]:
df["time"] = pd.to_datetime(df["time"], unit="ms", errors="coerce")

df["updated"] = pd.to_datetime(df["updated"], unit="ms", errors="coerce")

print(df[["time", "updated"]].head())

                     time                 updated
0 2021-01-01 00:01:39.400 2021-01-30 09:44:18.313
1 2021-01-01 00:04:10.210 2021-01-04 21:55:06.182
2 2021-01-01 00:12:19.760 2021-01-30 09:44:41.681
3 2021-01-01 00:14:07.580 2021-01-30 09:44:59.873
4 2021-01-01 00:16:24.950 2021-01-31 08:12:56.411

In [21]:
print(df.isnull().sum())
print("Duplicate rows:", df.duplicated().sum())

id                0
time              0
updated           0
latitude          0
longitude         0
depth_km          0
mag              60
magType          60
place             0
status            0
tsunami           0
alert        757861
felt         723685
cdi          723685
mmi          753308
sig               0
net               0
code              0
ids               0
sources           0
types             0
nst          208213
dmin         243184
rms              62
gap          179993
type              0
dtype: int64
Duplicate rows: 0

In [22]:
print(df[[
    "id",
    "time",
    "updated",
    "latitude",
    "longitude",
    "depth_km",
    "mag",
    "magType",
    "place",
    "status",
    "tsunami",
    "alert",
    "felt",
    "cdi",
    "mmi",
    "sig",
    "net",
    "code",
    "ids",
    "sources",
    "types",
    "nst",
    "dmin",
    "rms",
    "gap",
    "type"
]].head())

             id                    time                 updated   latitude  \
0  pr2021001027 2021-01-01 00:01:39.400 2021-01-30 09:44:18.313  17.995100
1    nc73505360 2021-01-01 00:04:10.210 2021-01-04 21:55:06.182  38.047333
2  pr2021001028 2021-01-01 00:12:19.760 2021-01-30 09:44:41.681  17.976000
3  pr2021001029 2021-01-01 00:14:07.580 2021-01-30 09:44:59.873  19.063100
4  pr2021001030 2021-01-01 00:16:24.950 2021-01-31 08:12:56.411  17.967600

   longitude  depth_km   mag magType                                   place  \
0   -67.0525      5.00  1.75      md    2 km NNW of La Parguera, Puerto Rico
1  -118.7285      5.25  1.89      md                    31km SE of Bodie, CA
2   -66.8420     13.00  1.89      md          3 km SW of Indios, Puerto Rico
3   -66.8555      8.00  3.14      md         63 km N of Hatillo, Puerto Rico
4   -66.8720     19.00  1.66      md  2 km ESE of Maria Antonia, Puerto Rico

     status  ...  net        code             ids  sources  \
0  reviewed  ...   pr  2021001027  ,pr2021001027,     ,pr,
1  reviewed  ...   nc    73505360    ,nc73505360,     ,nc,
2  reviewed  ...   pr  2021001028  ,pr2021001028,     ,pr,
3  reviewed  ...   pr  2021001029  ,pr2021001029,     ,pr,
4  reviewed  ...   pr  2021001030  ,pr2021001030,     ,pr,

                                            types   nst    dmin   rms    gap  \
0                             ,origin,phase-data,   4.0  0.0270  0.08  120.0
1  ,nearby-cities,origin,phase-data,scitech-link,  26.0  0.2693  0.09   90.0
2                             ,origin,phase-data,   6.0  0.2023  0.11  208.0
3                             ,origin,phase-data,  16.0  0.6482  0.52  284.0
4                             ,origin,phase-data,   4.0  0.1722  0.10  303.0

         type
0  earthquake
1  earthquake
2  earthquake
3  earthquake
4  earthquake

[5 rows x 26 columns]

In [23]:
print(df.info())
print(df.isnull().sum())

<class 'pandas.DataFrame'>
RangeIndex: 762117 entries, 0 to 762116
Data columns (total 26 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   id         762117 non-null  str
 1   time       762117 non-null  datetime64[ms]
 2   updated    762117 non-null  datetime64[ms]
 3   latitude   762117 non-null  float64
 4   longitude  762117 non-null  float64
 5   depth_km   762117 non-null  float64
 6   mag        762057 non-null  float64
 7   magType    762057 non-null  str
 8   place      762117 non-null  str
 9   status     762117 non-null  str
 10  tsunami    762117 non-null  int64
 11  alert      4256 non-null    str
 12  felt       38432 non-null   float64
 13  cdi        38432 non-null   float64
 14  mmi        8809 non-null    float64
 15  sig        762117 non-null  int64
 16  net        762117 non-null  str
 17  code       762117 non-null  str
 18  ids        762117 non-null  str
 19  sources    762117 non-null  str
 20  types      762117 non-null  str
 21  nst        553904 non-null  float64
 22  dmin       518933 non-null  float64
 23  rms        762055 non-null  float64
 24  gap        582124 non-null  float64
 25  type       762117 non-null  str
dtypes: datetime64[ms](2), float64(11), int64(2), str(11)
memory usage: 151.2 MB
None
id                0
time              0
updated           0
latitude          0
longitude         0
depth_km          0
mag              60
magType          60
place             0
status            0
tsunami           0
alert        757861
felt         723685
cdi          723685
mmi          753308
sig               0
net               0
code              0
ids               0
sources           0
types             0
nst          208213
dmin         243184
rms              62
gap          179993
type              0
dtype: int64

In [26]:
numeric_columns = ["nst", "dmin", "rms", "gap", "felt", "cdi", "mmi"]
for col in numeric_columns:
    df[col] = df[col].fillna(df[col].median())
    df["alert"] = df["alert"].fillna("Unknown")
    df["year"] = df["time"].dt.year
df["month"] = df["time"].dt.month
df["month_name"] = df["time"].dt.month_name()
print(df[["time", "year", "month", "month_name"]].head())

                     time  year  month month_name
0 2021-01-01 00:01:39.400  2021      1    January
1 2021-01-01 00:04:10.210  2021      1    January
2 2021-01-01 00:12:19.760  2021      1    January
3 2021-01-01 00:14:07.580  2021      1    January
4 2021-01-01 00:16:24.950  2021      1    January

In [29]:
def depth_category(depth):
    if depth < 70:
        return "Shallow"
    elif depth < 300:
        return "Intermediate"
    else:
        return "Deep"

df["depth_category"] = df["depth_km"].apply(depth_category)
print(df[["depth_km", "depth_category"]].head())
print(df["depth_category"].value_counts())

   depth_km depth_category
0      5.00        Shallow
1      5.25        Shallow
2     13.00        Shallow
3      8.00        Shallow
4     19.00        Shallow
depth_category
Shallow         688816
Intermediate     67107
Deep              6194
Name: count, dtype: int64

In [30]:
print(df.shape)
print(df.columns.tolist())

(762117, 30)
['id', 'time', 'updated', 'latitude', 'longitude', 'depth_km', 'mag', 'magType', 'place', 'status', 'tsunami', 'alert', 'felt', 'cdi', 'mmi', 'sig', 'net', 'code', 'ids', 'sources', 'types', 'nst', 'dmin', 'rms', 'gap', 'type', 'year', 'month', 'month_name', 'depth_category']

In [31]:
print(df.shape)
print(df.columns.tolist())

(762117, 30)
['id', 'time', 'updated', 'latitude', 'longitude', 'depth_km', 'mag', 'magType', 'place', 'status', 'tsunami', 'alert', 'felt', 'cdi', 'mmi', 'sig', 'net', 'code', 'ids', 'sources', 'types', 'nst', 'dmin', 'rms', 'gap', 'type', 'year', 'month', 'month_name', 'depth_category']

In [32]:
display(df.head())

,id,time,updated,latitude,longitude,depth_km,mag,magType,place,status,...,types,nst,dmin,rms,gap,type,year,month,month_name,depth_category
0,pr2021001027,2021-01-01 00:01:39.400,2021-01-30 09:44:18.313,17.995100,-67.0525,5.00,1.75,md,"2 km NNW of La Parguera, Puerto Rico",reviewed,...,",origin,phase-data,",4.0,0.0270,0.08,120.0,earthquake,2021,1,January,Shallow
1,nc73505360,2021-01-01 00:04:10.210,2021-01-04 21:55:06.182,38.047333,-118.7285,5.25,1.89,md,"31km SE of Bodie, CA",reviewed,...,",nearby-cities,origin,phase-data,scitech-link,",26.0,0.2693,0.09,90.0,earthquake,2021,1,January,Shallow
2,pr2021001028,2021-01-01 00:12:19.760,2021-01-30 09:44:41.681,17.976000,-66.8420,13.00,1.89,md,"3 km SW of Indios, Puerto Rico",reviewed,...,",origin,phase-data,",6.0,0.2023,0.11,208.0,earthquake,2021,1,January,Shallow
3,pr2021001029,2021-01-01 00:14:07.580,2021-01-30 09:44:59.873,19.063100,-66.8555,8.00,3.14,md,"63 km N of Hatillo, Puerto Rico",reviewed,...,",origin,phase-data,",16.0,0.6482,0.52,284.0,earthquake,2021,1,January,Shallow
4,pr2021001030,2021-01-01 00:16:24.950,2021-01-31 08:12:56.411,17.967600,-66.8720,19.00,1.66,md,"2 km ESE of Maria Antonia, Puerto Rico",reviewed,...,",origin,phase-data,",4.0,0.1722,0.10,303.0,earthquake,2021,1,January,Shallow

In [33]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:Aathiran@localhost/seismic_project"
)

print("MySQL connection created successfully")

MySQL connection created successfully

In [34]:
df.to_sql(
    "earthquakes",
    con=engine,
    if_exists="replace",
    index=False
)

print("Earthquake data successfully stored in MySQL")

Earthquake data successfully stored in MySQL

In [35]:
check_df = pd.read_sql(
    "SELECT * FROM earthquakes LIMIT 5",
    engine
)

display(check_df)

,id,time,updated,latitude,longitude,depth_km,mag,magType,place,status,...,types,nst,dmin,rms,gap,type,year,month,month_name,depth_category
0,pr2021001027,2021-01-01 00:01:39,2021-01-30 09:44:18,17.995100,-67.0525,5.00,1.75,md,"2 km NNW of La Parguera, Puerto Rico",reviewed,...,",origin,phase-data,",4.0,0.0270,0.08,120.0,earthquake,2021,1,January,Shallow
1,nc73505360,2021-01-01 00:04:10,2021-01-04 21:55:06,38.047333,-118.7285,5.25,1.89,md,"31km SE of Bodie, CA",reviewed,...,",nearby-cities,origin,phase-data,scitech-link,",26.0,0.2693,0.09,90.0,earthquake,2021,1,January,Shallow
2,pr2021001028,2021-01-01 00:12:20,2021-01-30 09:44:42,17.976000,-66.8420,13.00,1.89,md,"3 km SW of Indios, Puerto Rico",reviewed,...,",origin,phase-data,",6.0,0.2023,0.11,208.0,earthquake,2021,1,January,Shallow
3,pr2021001029,2021-01-01 00:14:08,2021-01-30 09:45:00,19.063100,-66.8555,8.00,3.14,md,"63 km N of Hatillo, Puerto Rico",reviewed,...,",origin,phase-data,",16.0,0.6482,0.52,284.0,earthquake,2021,1,January,Shallow
4,pr2021001030,2021-01-01 00:16:25,2021-01-31 08:12:56,17.967600,-66.8720,19.00,1.66,md,"2 km ESE of Maria Antonia, Puerto Rico",reviewed,...,",origin,phase-data,",4.0,0.1722,0.10,303.0,earthquake,2021,1,January,Shallow